# Generated by Django 4.2.15 on 2024-08-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_tag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
